version: '3.1'
services:
    mysql:
        image: 'mysql:8.0'
        volumes:
            - ./docker/mysql/data:/var/lib/mysql
        environment:
            - MYSQL_ROOT_PASSWORD=root
            - MYSQL_DATABASE=simple-php-orm
            - MYSQL_USER=appuser
            - MYSQL_PASSWORD=apppass
        ports:
            - '8082:3306'

    webserver:
        image: 'nginx:alpine'
        working_dir: /code
        volumes:
            - './code:/code'
            - './docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf'
        ports:
            - '8080:80'

    php-fpm:
        build: docker/php-fpm
        working_dir: /code
        volumes:
            - './code:/code'
            
    adminer:
        image: adminer
        restart: always
        ports:
          - 8081:8080
